### PR TITLE
Fix slack icon name is influenced by locale setting

### PR DESCRIPTION
**Pull request by r-ralph**
I use this slack bot with Japanese translation and [Slack Emoji Pokémon](https://github.com/Templarian/slack-emoji-pokemon).
However, icon text also translated and can't show correctly.

I fixed this problem by following solution.
1. Load English resource always.
2. Use values from English resource in `user_icon`

Before
before

After
after

### CODE REVIEW

**Comment by VincentCATILLON** [comment]
Ping @rubenmak

**Comment by rubenmak** [comment]
Thanks! Since github is acting a bit weird ovre my mobile phone connection, I quickly copied your changes into my code (otherwise I've had just merged it). I tweaked it a bit by adding an argument so you can actually chose a different locale for the emojis, default is English so should work!

It's on the development branch if you want to take a look, together with the connection reset. I'll take a look at a reported issue with the connection reset, and then merge it to master.

**Comment by rubenmak** [comment]
Merged onto master!

**Comment by r-ralph** [comment]
Thanks :)

**Pull request closed without merging**
